<div class="wrapper">
	<section id="topsection" class="grid">
		<div  class="col" style="background-image: url('vue/img/morgane-caprices-carre.jpg')">
			<div class="col-content"><p>Les caprices de Marianne</p></div>
		</div>
		<div  class="col" style="background-image:url('vue/img/treteaux couleurs-carre.jpg')">
			<div class="col-content"><p>Atelier Devineau</p></div>
		</div>
		<div  class="col" style="background-image:url('vue/img/photo intro theatre carre.jpg')">
			<div class="col-content"><p>Chut... Silences de Chet !</p></div>
		</div>
	</section>
</div>
<div id="separation">
	<div class="line-separator"></div>
	<a href="#">Dernièrement <i class="fa fa-caret-down" aria-hidden="true"></i></a>
	<div class="line-separator"></div>
</div>
<div class="wrapper">
	<section id="mainsection"  class="grid">
		<?php foreach ($derniers_projets as $projet): ?>
			<a href="projet.php?ref=<?=$projet['id_projet']; ?>"  class="col" style="background-image: url('vue/img/<?=$projet['url_img']; ?>')">
				<div class="col-content"><p><?=$projet['nom_projet']; ?></p></div>
			</a>
		<?php endforeach ?>
	</section>
</div>